version: '3.8'

services:
  backend:
    build: .
    container_name: manga_backend
    ports:
      - "8000:8000"
    volumes:
      - ./PDF:/app/PDF
      - ./.env:/app/.env
    restart: unless-stopped
    command: python web_server.py

  frontend:
    build:
      context: ./web_client_next
      dockerfile: Dockerfile
    container_name: manga_frontend
    ports:
      - "3000:3000" # Next.js exposed on port 3000
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
